Parameters:
  PrerenderToken:
    Type: String
  OriginDomain:
    Type: String
Resources:
  LambdaEdgeExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - edgelambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: logging
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
  SetPrerenderHeader:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "index.handler"
      Role:
        Fn::GetAtt:
          - "LambdaEdgeExecutionRole"
          - "Arn"
      Code:
        ZipFile:
          !Sub |
            'use strict';
            /* change the version number below whenever this code is modified */
            exports.handler = (event, context, callback) => {
                const request = event.Records[0].cf.request;
                const headers = request.headers;
                const user_agent = headers['user-agent'];
                const host = headers['host'];
                if (user_agent && host) {
                  if (/baiduspider|Facebot|facebookexternalhit|twitterbot|rogerbot|linkedinbot|embedly|quora link preview|showyoubot|outbrain|pinterest|slackbot|vkShare|W3C_Validator/.test(user_agent[0].value)) {
                    headers['x-prerender-token'] = [{ key: 'X-Prerender-Token', value: '${PrerenderToken}'}];
                    headers['x-prerender-host'] = [{ key: 'X-Prerender-Host', value: host[0].value}];
                  }
                }
                callback(null, request);
            };
      Runtime: "nodejs6.10"
  SetPrerenderHeaderVersion2:
    Type: "AWS::Lambda::Version"
    Properties:
      FunctionName:
        Ref: "SetPrerenderHeader"
      Description: "SetPrerenderHeader"
  RedirectToPrerender:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "index.handler"
      Role:
        Fn::GetAtt:
          - "LambdaEdgeExecutionRole"
          - "Arn"
      Code:
        ZipFile: |
          'use strict';
          /* change the version number below whenever this code is modified */
          exports.handler = (event, context, callback) => {
               const request = event.Records[0].cf.request;
               if (request.headers['x-prerender-token'] && request.headers['x-prerender-host']) {
                 request.origin = {
                     custom: {
                         domainName: 'service.prerender.io',
                         port: 443,
                         protocol: 'https',
                         readTimeout: 20,
                         keepaliveTimeout: 5,
                         customHeaders: {},
                         sslProtocols: ['TLSv1', 'TLSv1.1'],
                         path: '/https%3A%2F%2F' + request.headers['x-prerender-host'][0].value
                     }
                 };
              }
              callback(null, request);
          };
      Runtime: "nodejs6.10"
  RedirectToPrerenderVersion1:
    Type: "AWS::Lambda::Version"
    Properties:
      FunctionName:
        Ref: "RedirectToPrerender"
      Description: "RedirectToPrerender"
  CloudFront:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          Compress: true
          MinTTL: 31536000
          DefaultTTL: 31536000
          ForwardedValues:
            QueryString: false
            Headers:
              - "X-Prerender-Token"
              - "X-Prerender-Host"
          TargetOriginId: origin
          ViewerProtocolPolicy : allow-all
          LambdaFunctionAssociations:
            - EventType: viewer-request
              LambdaFunctionARN: !Join [ ":", [ !GetAtt [SetPrerenderHeader, Arn], !GetAtt [SetPrerenderHeaderVersion2, Version] ] ]
            - EventType: origin-request
              LambdaFunctionARN: !Join [ ":", [ !GetAtt [RedirectToPrerender, Arn], !GetAtt [RedirectToPrerenderVersion1, Version] ] ]
        Enabled: true
        HttpVersion: http2
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: https-only
            DomainName: !Ref OriginDomain
            Id: origin
        PriceClass: PriceClass_100
